# Generated by Django 5.0.2 on 2024-02-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='decription',
            new_name='description',
        ),
    ]
