# Generated by Django 5.0.2 on 2024-02-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_decription_item_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
